### PR TITLE
Beta 1.6

### PR DESCRIPTION
**Pull request by frikilax**
## Fixed
- [PORTAL] URL link for 'lost password'
- [PORTAL] Error while retrieving user from mail while loading 'lost password' URL
- [PORTAL] [SELF_SERVICE] Password reset email missed a '/' in the reset URL
- [PORTAL] Avoid strange redirections during authentication (caused by previous queries)
- [UTILS] [AES] Padding errors 
- [TOTP] Various errors preventing TOTP to work properly
- [PORTAL] Only allow user's session at the end of the whole process, permitting SSOForward to work as expected when Learning values are asked to the user
- [SSOForward] Use response.text to avoid errors when getting and parsing forms
- [SYNTAX] Code cleanup and syntax corrections
- [TOTP] Avoid errors during disconnexion when portal has no OTP configured
- [LDAP] Correctly create group in LDAP when IDP portal must add a new user to it
- [LDAP] Don't apply sanitation on group enumerations in code
- [PORTAL] Redirect user to workflow's public_dir instead of previous page in case of (re)authentication failure
- [PORTAL] Captcha field now works as intended
- [PORTAL] [SELF_SERVICE] reset password key is now hidden in 'password change' form
- [LDAP] Avoid decoding errors when formatting data from user search (could result in 500)
- [PORTAL] Correctly redirect client on successful authentication on a portal without SSOForward
- [CLUSTER] [JOIN] Correctly sync Redis between joining nodes of a same cluster

## Removed
- [SECADM] Obsolete 'node' rule

## Added
- [IDP] [API] Deny username changes on an existing user entry
- [DARWIN] [API] Now possible to get a Policy by its name
- [CLUSTER] [JOIN] Sync master's secret key between joining nodes to avoid encrypion/decryption problems between nodes of a same cluster

## Changed
- [PORTAL] [SELF_SERVICE] Don't make a difference when returning for a password reset request between a valid and an invalid email (prevent user enumeration via email)
- [PORTAL] [SELF_SERVICE] Improve errors reporting during password reset request
- [PORTAL] [SELF_SERVICE] Password reset URLs are now available for 3 days
- [TOOLS] [LDAP] Cleaner errors
- [PORTAL] [SELF_SERVICE] Refuse empty password when changing them
- [OPENID] OpenID repositories can no longer have the same 'client_id' (duplicates will be deleted, and replaced with the remaining object when used)

### CODE REVIEW

**Comment by advbarbieux** [comment]
In `vulture_os/toolkit/auth/ldap_client.py`, the following code:

`
for subval in val:
if isinstance(subval, bytes):
    i = val.index(subval)
    val.pop(i)
    val.insert(i, subval.decode('utf-8'))
`

could be made simpler and more efficient, as follows:

`
for i, subval in enumerate(val):
if isinstance(subval, bytes):
    val[i] = subval.decode('utf-8'))
`

**Comment by advbarbieux** [comment]
In [commit 6335d76ddfd391ec0a9507ebd48d9c81faca1814](https://github.com/VultureProject/vulture-gui/pull/152/commits/6335d76ddfd391ec0a9507ebd48d9c81faca1814), an `AssertionError` is used, but `AssertionError`s are not meant for error reporting AFAIK.

A dedicated exception type should be used instead IMO.

**Comment by advbarbieux** [comment]
The rest of this PR looks OK to me.

**Review by KGuillemot — APPROVED** [review]

**Review by HugoSoszynski — APPROVED** [review]

**Review by advbarbieux — COMMENTED** [review]
I don't want to sound paranoid, but in `vulture_os/authentication/ldap/tools.py`, isn't there a possibility that `attrs[ldap_repository.user_attr]` could be an empty list, in which case line 207 would trigger an `IndexError`?
The rest looks OK to me.

**Comment by frikilax** [comment]
> I don't want to sound paranoid, but in `vulture_os/authentication/ldap/tools.py`, isn't there a possibility that `attrs[ldap_repository.user_attr]` could be an empty list, in which case line 207 would trigger an `IndexError`? The rest looks OK to me.

good call

**Review by advbarbieux — APPROVED** [review]

**Pull request merged**
